// src/types.ts
// Type definitions for the Storage layer

export type NoteID = string

/**
 * Note metadata stored in database
 * ID is ONLY in DB, never injected into files
 */
export interface NoteMeta {
  note_id: NoteID // UUID generated by system
  path: string // vault-relative POSIX path, e.g. "notes/todo.md"
  display_name: string // filename or title from frontmatter
  folder_path: string // vault-relative folder
  created_at: number // epoch ms
  updated_at: number // epoch ms
  content_hash?: string // SHA256 for conflict detection
  source?: "md" | "pdf" | "import"
  deleted_at?: number | null // soft delete timestamp
}

/**
 * Full note with content + metadata
 */
export interface NoteWithContent {
  meta: NoteMeta
  content: string
  userFrontmatter?: Record<string, any> // User's original frontmatter
}

/**
 * Vault statistics
 */
export interface VaultStats {
  totalNotes: number
  totalFolders: number
  vaultPath: string
  lastScan: number
  storageVersion: string
}

/**
 * Event payloads
 */
export interface VaultReadyPayload {
  vaultPath: string
  totalNotes: number
  totalFolders: number
  scanTimeMs: number
}

export interface NoteCreatedPayload {
  note_id: NoteID
  path: string
  folder_path: string
  display_name: string
  created_at: number
  source: "internal" | "external"
}

export interface NoteUpdatedPayload {
  note_id: NoteID
  path: string
  updated_at: number
  content_hash: string
  source: "internal" | "external"
}

export interface NoteDeletedPayload {
  note_id: NoteID
  path: string
  trashed: boolean
  source: "internal" | "external"
}

export interface ConflictDetectedPayload {
  note_id: NoteID
  path: string
  dbHash: string
  diskHash: string
  conflictPath: string
  timestamp: number
}

export interface FolderMovedPayload {
  oldPath: string
  newPath: string
  affectedNotes: number
}

/**
 * Conflict information
 */
export interface Conflict {
  note_id: NoteID
  originalPath: string
  conflictPath: string
  timestamp: number
  dbHash: string
  diskHash: string
  resolved: boolean
}

/**
 * Import report
 */
export interface ImportReport {
  totalFiles: number
  imported: number
  skipped: number
  errors: string[]
  duration: number
}