// src/types.ts
// Type definitions for the Storage layer

export type NoteID = string
export type FolderID = string

/**
 * Status of a note in the RAG embedding pipeline
 * - pending:  note exists but has never been embedded
 * - indexed:  content is in ChromaDB and up-to-date
 * - stale:    content changed since last embedding (updated_at > last_embedded_at)
 * - error:    last embedding attempt failed
 */
export type EmbeddingStatus = "pending" | "indexed" | "stale" | "error"

/**
 * Note metadata stored in database
 * ID is ONLY in DB, never injected into files
 */
export interface NoteMeta {
  note_id: NoteID         // UUID generated by system
  path: string            // vault-relative POSIX path, e.g. "notes/todo.md"
  display_name: string    // filename or title from frontmatter
  folder_path: string     // vault-relative folder, "" for root
  created_at: number      // epoch ms
  updated_at: number      // epoch ms
  content_hash?: string   // SHA256 for conflict detection
  source?: "md" | "pdf" | "import"
  deleted_at?: number | null    // soft delete timestamp
  embedding_status?: EmbeddingStatus  // RAG pipeline state
  last_embedded_at?: number | null    // epoch ms of last successful embed
}

/**
 * A folder tracked in the database
 */
export interface Folder {
  folder_id: FolderID   // UUID
  path: string          // vault-relative POSIX path, e.g. "projects/work"
  name: string          // display name (last path segment)
  parent_path: string   // parent folder path, "" for root
  created_at: number    // epoch ms
  sort_order: number    // manual sort position
  icon?: string         // optional emoji or icon name
  pinned: boolean       // pinned to top of sidebar
}

/**
 * Options for listing notes with pagination
 */
export interface ListNotesOptions {
  folderPath?: string   // filter by folder
  offset?: number       // pagination offset
  limit?: number        // max results (default: all)
  orderBy?: "updated_at" | "created_at" | "display_name"
  direction?: "asc" | "desc"
}

/**
 * Lightweight note info returned for bulk RAG operations
 * Avoids loading full content unnecessarily
 */
export interface RAGNoteInfo {
  meta: NoteMeta
  content: string
}

/**
 * Full note with content + metadata
 */
export interface NoteWithContent {
  meta: NoteMeta
  content: string
  userFrontmatter?: Record<string, any> // User's original frontmatter
}

/**
 * Vault statistics
 */
export interface VaultStats {
  totalNotes: number
  totalFolders: number
  vaultPath: string
  lastScan: number
  storageVersion: string
}

// ==================== EVENT PAYLOADS ====================

export interface VaultReadyPayload {
  vaultPath: string
  totalNotes: number
  totalFolders: number
  scanTimeMs: number
}

export interface NoteCreatedPayload {
  note_id: NoteID
  path: string
  folder_path: string
  display_name: string
  created_at: number
  source: "internal" | "external"
}

export interface NoteUpdatedPayload {
  note_id: NoteID
  path: string
  updated_at: number
  content_hash: string
  source: "internal" | "external"
}

export interface NoteDeletedPayload {
  note_id: NoteID
  path: string
  trashed: boolean
  source: "internal" | "external"
}

export interface NoteRenamedPayload {
  note_id: NoteID
  oldPath: string
  newPath: string
  oldDisplayName: string
  newDisplayName: string
}

export interface NoteMovedPayload {
  note_id: NoteID
  oldPath: string
  newPath: string
  oldFolderPath: string
  newFolderPath: string
}

export interface ConflictDetectedPayload {
  note_id: NoteID
  path: string
  dbHash: string
  diskHash: string
  conflictPath: string
  timestamp: number
}

export interface FolderCreatedPayload {
  folder_id: FolderID
  path: string
  name: string
  parent_path: string
}

export interface FolderRenamedPayload {
  folder_id: FolderID
  oldPath: string
  newPath: string
  oldName: string
  newName: string
  affectedNotes: number
}

export interface FolderDeletedPayload {
  folder_id: FolderID
  path: string
  affectedNotes: number
}

export interface FolderMovedPayload {
  oldPath: string
  newPath: string
  affectedNotes: number
}

// ==================== MISC ====================

/**
 * Conflict information
 */
export interface Conflict {
  note_id: NoteID
  originalPath: string
  conflictPath: string
  timestamp: number
  dbHash: string
  diskHash: string
  resolved: boolean
}

/**
 * Import report
 */
export interface ImportReport {
  totalFiles: number
  imported: number
  skipped: number
  errors: string[]
  duration: number
}

